[package]
name = "advent-of-code-24"
version = "0.1.0"
edition = "2021"


[workspace]
members = ["day1", "day10", "day2", "day3", "day4", "day5", "day6", "day7", "day8", "day9", "utils"]


[workspace.dependencies]
grid = "0.15.0"
itertools = "0.13.0"
